"""Contracts and storage for the Agent Improvement Lab."""

from agent_improvement_lab.calibration import (
    CalibrationError,
    calculate_judge_metrics,
    compare_judge_calibrations,
    create_judge_calibration_dataset,
    identify_judge_review_targets,
)
from agent_improvement_lab.contracts.calibration import (
    CalibrationLabel,
    JudgeCalibrationCase,
    JudgeCalibrationDataset,
    JudgeCalibrationMetrics,
    JudgeCalibrationVerdict,
    JudgeReviewReason,
    JudgeReviewTarget,
    JudgeRubric,
    JudgeRubricComparison,
)
from agent_improvement_lab.contracts.candidates import (
    AgentCandidate,
    ArtifactEdit,
    CandidateChange,
    CandidateChangeSummary,
    CandidateGenerationRequest,
    CandidateLineage,
    CandidateScope,
    CandidateStatus,
    GeneratedCandidatePlan,
    PromptArtifact,
    PromptArtifactKind,
)
from agent_improvement_lab.contracts.cases import (
    CaseProvenance,
    DatasetSplit,
    DatasetVersion,
    EvaluationCaseRef,
    NumericRange,
    RiskLevel,
    ToolCallExpectation,
)
from agent_improvement_lab.contracts.evaluation import (
    AggregateGroup,
    CaseEvaluationResult,
    LabEvaluationReport,
)
from agent_improvement_lab.contracts.experiments import (
    ActiveCandidatePointer,
    BaselineComparison,
    ComparisonMetric,
    ComparisonPolicy,
    ComparisonVerdict,
    ExperimentRun,
    PromotionDecision,
    PromotionEvaluation,
    PromotionGateKind,
    PromotionGateResult,
    PromotionOutcome,
    PromotionPolicy,
    RunManifest,
)
from agent_improvement_lab.contracts.failures import (
    EvaluationFailure,
    EvaluationScore,
    FailureCluster,
    HumanAnnotation,
)
from agent_improvement_lab.contracts.sessions import SessionEvaluationResult, SessionSummary
from agent_improvement_lab.contracts.traces import AgentTrace, SessionTrace, TraceSummary
from agent_improvement_lab.dashboard import (
    DashboardQueryService,
    EvaluatorView,
    ExperimentView,
    FailureView,
    PromotionView,
    QueryError,
    SessionView,
    ToolCallView,
    TraceView,
    summarize_trace,
)
from agent_improvement_lab.promotion import PromotionEngine, PromotionError, PromotionService

__all__ = [
    "AgentCandidate",
    "AgentTrace",
    "ActiveCandidatePointer",
    "AggregateGroup",
    "ArtifactEdit",
    "BaselineComparison",
    "CandidateChange",
    "CandidateChangeSummary",
    "CandidateGenerationRequest",
    "CandidateLineage",
    "CandidateScope",
    "CaseProvenance",
    "CaseEvaluationResult",
    "CalibrationError",
    "CandidateStatus",
    "CalibrationLabel",
    "ComparisonMetric",
    "ComparisonPolicy",
    "ComparisonVerdict",
    "DatasetSplit",
    "DatasetVersion",
    "DashboardQueryService",
    "EvaluatorView",
    "EvaluationCaseRef",
    "EvaluationFailure",
    "EvaluationScore",
    "ExperimentRun",
    "ExperimentView",
    "FailureCluster",
    "FailureView",
    "GeneratedCandidatePlan",
    "HumanAnnotation",
    "JudgeCalibrationCase",
    "JudgeCalibrationDataset",
    "JudgeCalibrationMetrics",
    "JudgeCalibrationVerdict",
    "JudgeReviewReason",
    "JudgeReviewTarget",
    "JudgeRubric",
    "JudgeRubricComparison",
    "PromotionEngine",
    "PromotionError",
    "PromotionService",
    "PromotionView",
    "PromptArtifact",
    "PromptArtifactKind",
    "PromotionDecision",
    "PromotionEvaluation",
    "PromotionGateKind",
    "PromotionGateResult",
    "PromotionOutcome",
    "PromotionPolicy",
    "RiskLevel",
    "QueryError",
    "RunManifest",
    "NumericRange",
    "SessionEvaluationResult",
    "SessionSummary",
    "SessionTrace",
    "SessionView",
    "ToolCallExpectation",
    "ToolCallView",
    "TraceSummary",
    "TraceView",
    "LabEvaluationReport",
    "calculate_judge_metrics",
    "compare_judge_calibrations",
    "create_judge_calibration_dataset",
    "identify_judge_review_targets",
    "summarize_trace",
]

__version__ = "0.1.0"
